name: Publish package
on:
  push:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test

  release:
    runs-on: ubuntu-22.04
    needs: qa
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@cosmic-tiger-au"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: release
        run: pnpm semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
