name: Discord Release Notifier
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: sillyangel/releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "15277667"
          username: "GH Releases"
          avatar_url: "https://raw.githubusercontent.com/Cosmic-Tiger-AU/.github/main/profile/tiger-in-office.webp"
